core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls'), name="frontend"),
    path('inventory/', include('inventory.urls'), name = "inventory"),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventory/urls.py
from os import name
from django.urls import path, include
from django.views.generic import TemplateView
from .views  import *


app_name = "inventory"

urlpatterns = [
    path('', TemplateView.as_view(template_name =  'inventory/index.html') , name="index"),

    # category
    path('category-list', CategoryList.as_view(template_name="inventory/category-list.html"), name="cat-list"),
    path('category/add/', CategoryCreateView.as_view(template_name = "inventory/createview.html"), name='cat-add'),
    path('category/<int:pk>/', CategoryUpdateView.as_view(template_name = "inventory/createview.html"), name='cat-update'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(template_name = "inventory/deleteview.html"), name='cat-delete'),

    # brand

    path('brand-list', BrandList.as_view(template_name="inventory/brand-list.html"), name="brand-list"),
    path('brand/add/', BrandCreateView.as_view(template_name = "inventory/createview.html"), name='brand-add'),
    path('brand/<int:pk>/', BrandUpdateView.as_view(template_name = "inventory/createview.html"), name='brand-update'),
    path('brand/<int:pk>/delete/', BrandDeleteView.as_view(template_name = "inventory/deleteview.html"), name='brand-delete'),

    # attribute (atb)

    path('atb-list', AtbList.as_view(template_name="inventory/atb-list.html"), name="atb-list"),
    path('atb/add/', AtbCreateView.as_view(template_name = "inventory/createview.html"), name='atb-add'),
    path('atb/<int:pk>/', AtbUpdateView.as_view(template_name = "inventory/createview.html"), name='atb-update'),
    path('atb/<int:pk>/delete/', AtbDeleteView.as_view(template_name = "inventory/deleteview.html"), name='atb-delete'),

    # products 

    path('prod-list', ProdList.as_view(template_name="inventory/prod-list.html"), name="prod-list"),
    path('prod/add/', ProdCreateView.as_view(template_name = "inventory/createview.html"), name='prod-add'),
    path('prod/<int:pk>/', ProdUpdateView.as_view(template_name = "inventory/createview.html"), name='prod-update'),
    path('prod/<int:pk>/delete/', ProdDeleteView.as_view(template_name = "inventory/deleteview.html"), name='prod-delete'),

    # inventories (inv)

    path('inv-list', InvList.as_view(template_name="inventory/inv-list.html"), name="inv-list"),
    path('inv/add/', InvCreateView.as_view(template_name = "inventory/createview.html"), name='inv-add'),
    path('inv/<int:pk>/', InvUpdateView.as_view(template_name = "inventory/createview.html"), name='inv-update'),
    path('inv/<int:pk>/delete/', InvDeleteView.as_view(template_name = "inventory/deleteview.html"), name='inv-delete'),

]

inventory/models.py
from pickle import TRUE
from django.db import models
from datetime import datetime, timedelta
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.
class Categories(models.Model) :
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self) -> str:
        return self.title


class Attributes(models.Model) :
    value = models.CharField(max_length=100)
    def __str__(self) -> str:
        return self.value

class Brand(models.Model) :
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name


class Product(models.Model) :
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=255)
    image = models.ImageField(upload_to ="images/", default="images/default.png")
    # thumbnail
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(100, 100)],
                                      format='JPEG',
                                      options={'quality': 60})


    # foreign keys
    category = models.ManyToManyField(Categories)
    brand = models.ForeignKey(Brand, on_delete=models.RESTRICT)

    def __str__(self) -> str:
        return self.title



class ProductInventory(models.Model) :

    class Variants(models.IntegerChoices) :
        pro = 3
        native = 2
        lite = 1

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version = models.SlugField(unique=True, max_length=100)
    # attributes
    customAttribute = models.ForeignKey(Attributes, on_delete=models.RESTRICT, blank=True, null=True)
    variant = models.IntegerField(choices=Variants.choices, default=2)   

    # prices
    price = models.IntegerField()

    # stock
    stock = models.IntegerField(default=0)
    sold = models.IntegerField(default=0)
    debitDate = models.DateTimeField(default=datetime.utcnow()+timedelta(hours=5.5), 
    help_text=_(
        "format: required, YYYY-MM-DD HH:MN:SC (2022-01-19 17:29:19) "
    ),

    )
    creditDate = models.DateTimeField(default=datetime.utcnow()+timedelta(hours=5.5),
    help_text=_(
    "format: required, YYYY-MM-DD HH:MN:SC (2022-01-19 17:29:19) "
    ),
    )


    def __str__(self) -> str:
        return self.version

inventory/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import *
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy


class CategoryList(ListView) :
    model = Categories


class CategoryCreateView(CreateView):
    model = Categories
    fields = '__all__'
    success_url = reverse_lazy('inventory:cat-list')

class CategoryCreateView(CreateView):
    model = Categories
    fields = '__all__'
    success_url = reverse_lazy('inventory:cat-list')

class CategoryUpdateView(UpdateView):
    model = Categories
    fields = '__all__'
    success_url = reverse_lazy('inventory:cat-list')

class CategoryDeleteView(DeleteView):
    model = Categories
    success_url = reverse_lazy('inventory:cat-list')


# brand


class BrandList(ListView) :
    model = Brand


class BrandCreateView(CreateView):
    model = Brand
    fields = '__all__'
    success_url = reverse_lazy('inventory:brand-list')

class BrandCreateView(CreateView):
    model = Brand
    fields = '__all__'
    success_url = reverse_lazy('inventory:brand-list')


class BrandUpdateView(UpdateView):
    model = Brand
    fields = '__all__'
    success_url = reverse_lazy('inventory:brand-list')

class BrandDeleteView(DeleteView):
    model = Brand
    success_url = reverse_lazy('inventory:brand-list')


# Attribute


class AtbList(ListView) :
    model = Attributes


class AtbCreateView(CreateView):
    model = Attributes
    fields = '__all__'
    success_url = reverse_lazy('inventory:atb-list')

class AtbCreateView(CreateView):
    model = Attributes
    fields = '__all__'
    success_url = reverse_lazy('inventory:atb-list')


class AtbUpdateView(UpdateView):
    model = Attributes
    fields = '__all__'
    success_url = reverse_lazy('inventory:atb-list')

class AtbDeleteView(DeleteView):
    model = Attributes
    success_url = reverse_lazy('inventory:atb-list')


# products (prod)


class ProdList(ListView) :
    model = Product


class ProdCreateView(CreateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('inventory:prod-list')

class ProdCreateView(CreateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('inventory:prod-list')


class ProdUpdateView(UpdateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('inventory:prod-list')

class ProdDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('inventory:prod-list')


# inventories



class InvList(ListView) :
    model = ProductInventory


class InvCreateView(CreateView):
    model = ProductInventory
    fields = '__all__'
    success_url = reverse_lazy('inventory:inv-list')

class InvCreateView(CreateView):
    model = ProductInventory
    fields = '__all__'
    success_url = reverse_lazy('inventory:inv-list')


class InvUpdateView(UpdateView):
    model = ProductInventory
    fields = '__all__'
    success_url = reverse_lazy('inventory:inv-list')

class InvDeleteView(DeleteView):
    model = ProductInventory
    success_url = reverse_lazy('inventory:inv-list')

templates/inventory/atb-list.html
{% extends 'base.html' %}

{% block content %}

    
<a href="{% url 'inventory:atb-add' %}" class="btn btn-primary">
    Create a new Attribute
</a>

<br>
<hr>

Already Created Objects are - 
<br> 
<p>
    To delete a attribute make sure all the product using it is deleted else you will recieve error !
</p>

<ul>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Attribute</th>
            <th scope="col">View</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <th scope="row">{{object.value}}</th>
            <td>
                <a href="{% url 'inventory:atb-update' object.id %}" >
                    edit
                </a>
            </td>
            <td>
                <a href="{% url 'inventory:atb-delete' object.id %}">
                    delete
                </a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
    </table>
      

</ul>


{% endblock %}

templates/inventory/brand-list.html
{% extends 'base.html' %}

{% block content %}

    
<a href="{% url 'inventory:brand-add' %}" class="btn btn-primary">
    Create a new brand
</a>

<br>
<hr>

Already Created Objects are - 
<br> 
<p>
    To delete a brand make sure all the product using it is deleted else you will recieve error !
</p>

<ul>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Brand</th>
            <th scope="col">View</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <th scope="row">{{object.name}}</th>
            <td>
                <a href="{% url 'inventory:brand-update' object.id %}" >
                    edit
                </a>
            </td>
            <td>
                <a href="{% url 'inventory:brand-delete' object.id %}">
                    delete
                </a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
    </table>
      

</ul>


{% endblock %}

templates/inventory/category-list.html
{% extends 'base.html' %}

{% block content %}

    
<a href="{% url 'inventory:cat-add' %}" class="btn btn-primary">
    Create a new category
</a>




<br>
<hr>

Already Created Objects are - 

<p>
    To delete a category make sure all the product using it is deleted else you will recieve error !
</p>

<ul>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Category</th>
            <th scope="col">View</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <th scope="row">{{object.title}}</th>
            <td>
                <a href="{% url 'inventory:cat-update' object.id %}" >
                    edit
                </a>
            </td>
            <td>
                <a href="{% url 'inventory:cat-delete' object.id %}">
                    delete
                </a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
    </table>
      

</ul>


{% endblock %}

templates/inventory/createview.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        {% load crispy_forms_tags %}
        <div class="mb-3">
            <form method="POST" enctype="multipart/form-data" class="bootstrap4">
                {% csrf_token %}
                {{ form | crispy }}
                <br>
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
    </div>

{% endblock %}

templates/inventory/deleteview.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<form method="post"  class="bootstrap4">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>    
    <input type="submit" value="Confirm" class="btn btn-danger">
</form>

{% endblock %}

templates/inventory/index.html
{% extends 'base.html' %}

{% block content %}

Perform CRUD on any of the following Models - <br>
Please note every product must belong to a category, so before creating a product please select a category, if the corrosponding category doesnt already exist.

<ul>
    <li>
        <a href="{% url 'inventory:cat-list' %}">Categories</a>
    </li>
    <li>
        <a href="{% url 'inventory:brand-list' %}"> Brand </a>
    </li>
    <li>
        <a href="{% url 'inventory:atb-list' %}">Attributes</a>
    </li>

    <li>
        <a href="{% url 'inventory:prod-list' %}">
        Products
        </a>
    </li>

    <li>
        <a href="{% url 'inventory:inv-list' %}">
        Product Inventory
        </a>
    </li>
</ul>

{% endblock %}

templates/inventory/inv-list.html
{% extends 'base.html' %}

{% block content %}

    
<a href="{% url 'inventory:inv-add' %}" class="btn btn-primary">
    Create a new Inventory
</a>

<br>
<hr>

Already Created Objects are - 
<br> 

<ul>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Inventory</th>
            <th scope="col">View</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <th scope="row">{{object.version}}</th>
            <td>
                <a href="{% url 'inventory:inv-update' object.id %}" >
                    edit
                </a>
            </td>
            <td>
                <a href="{% url 'inventory:inv-delete' object.id %}">
                    delete
                </a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
    </table>
      

</ul>


{% endblock %}

templates/inventory/prod-list.html
{% extends 'base.html' %}

{% block content %}

    
<a href="{% url 'inventory:prod-add' %}" class="btn btn-primary">
    Create a new Product
</a>

<br>
<hr>

Already Created Objects are - 
<br> 
<p>
    To delete a product make sure all the inventories using it is deleted else you will recieve error !
</p>

<ul>

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">View</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
          <tr>
            <th scope="row">{{object.title}}</th>
            <td>
                <a href="{% url 'inventory:prod-update' object.id %}" >
                    edit
                </a>
            </td>
            <td>
                <a href="{% url 'inventory:prod-delete' object.id %}">
                    delete
                </a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
    </table>
      

</ul>


{% endblock %}