core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls'), name="frontend"),
    path('inventory/', include('inventory.urls'), name = "inventory"),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/urls.py
from os import name
from django.urls import path, include
from django.views.generic import TemplateView
from .  import views


app_name = "frontend"

urlpatterns = [
    path('', TemplateView.as_view(template_name =  'frontend/index.html') , name="home"),
    path("categories/", views.categoriesList , name = "categories-list" ),

    path("product/<str:slug>", views.productPage, name="productPage"),
    path("inventories/<str:slug>", views.inventories, name="inventories"),


    path("product/", views.listProduct, name="list-products"),
    path("product/version/<str:slug>", views.inventory, name="inventory"),
]

inventory/urls.py
from os import name
from django.urls import path, include
from django.views.generic import TemplateView
from .views  import *


app_name = "inventory"

urlpatterns = [
    path('', TemplateView.as_view(template_name =  'inventory/index.html') , name="index"),

    # category
    path('category-list', CategoryList.as_view(template_name="inventory/category-list.html"), name="cat-list"),
    path('category/add/', CategoryCreateView.as_view(template_name = "inventory/createview.html"), name='cat-add'),
    path('category/<int:pk>/', CategoryUpdateView.as_view(template_name = "inventory/createview.html"), name='cat-update'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(template_name = "inventory/deleteview.html"), name='cat-delete'),

    # brand

    path('brand-list', BrandList.as_view(template_name="inventory/brand-list.html"), name="brand-list"),
    path('brand/add/', BrandCreateView.as_view(template_name = "inventory/createview.html"), name='brand-add'),
    path('brand/<int:pk>/', BrandUpdateView.as_view(template_name = "inventory/createview.html"), name='brand-update'),
    path('brand/<int:pk>/delete/', BrandDeleteView.as_view(template_name = "inventory/deleteview.html"), name='brand-delete'),

    # attribute (atb)

    path('atb-list', AtbList.as_view(template_name="inventory/atb-list.html"), name="atb-list"),
    path('atb/add/', AtbCreateView.as_view(template_name = "inventory/createview.html"), name='atb-add'),
    path('atb/<int:pk>/', AtbUpdateView.as_view(template_name = "inventory/createview.html"), name='atb-update'),
    path('atb/<int:pk>/delete/', AtbDeleteView.as_view(template_name = "inventory/deleteview.html"), name='atb-delete'),

    # products 

    path('prod-list', ProdList.as_view(template_name="inventory/prod-list.html"), name="prod-list"),
    path('prod/add/', ProdCreateView.as_view(template_name = "inventory/createview.html"), name='prod-add'),
    path('prod/<int:pk>/', ProdUpdateView.as_view(template_name = "inventory/createview.html"), name='prod-update'),
    path('prod/<int:pk>/delete/', ProdDeleteView.as_view(template_name = "inventory/deleteview.html"), name='prod-delete'),

    # inventories (inv)

    path('inv-list', InvList.as_view(template_name="inventory/inv-list.html"), name="inv-list"),
    path('inv/add/', InvCreateView.as_view(template_name = "inventory/createview.html"), name='inv-add'),
    path('inv/<int:pk>/', InvUpdateView.as_view(template_name = "inventory/createview.html"), name='inv-update'),
    path('inv/<int:pk>/delete/', InvDeleteView.as_view(template_name = "inventory/deleteview.html"), name='inv-delete'),

]

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'frontend:home' %}">IMS</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'frontend:categories-list' %}">Categories</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'frontend:list-products' %}">Product</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'inventory:index' %}">Modify Database</a>
          </li>

        </ul>
      </div>
    </div>
</nav>