core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls'), name="frontend"),
    path('inventory/', include('inventory.urls'), name = "inventory"),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/urls.py
from os import name
from django.urls import path, include
from django.views.generic import TemplateView
from .  import views


app_name = "frontend"

urlpatterns = [
    path('', TemplateView.as_view(template_name =  'frontend/index.html') , name="home"),
    path("categories/", views.categoriesList , name = "categories-list" ),

    path("product/<str:slug>", views.productPage, name="productPage"),
    path("inventories/<str:slug>", views.inventories, name="inventories"),


    path("product/", views.listProduct, name="list-products"),
    path("product/version/<str:slug>", views.inventory, name="inventory"),
]

inventory/urls.py
from os import name
from django.urls import path, include
from django.views.generic import TemplateView
from .views  import *


app_name = "inventory"

urlpatterns = [
    path('', TemplateView.as_view(template_name =  'inventory/index.html') , name="index"),

    # category
    path('category-list', CategoryList.as_view(template_name="inventory/category-list.html"), name="cat-list"),
    path('category/add/', CategoryCreateView.as_view(template_name = "inventory/createview.html"), name='cat-add'),
    path('category/<int:pk>/', CategoryUpdateView.as_view(template_name = "inventory/createview.html"), name='cat-update'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(template_name = "inventory/deleteview.html"), name='cat-delete'),

    # brand

    path('brand-list', BrandList.as_view(template_name="inventory/brand-list.html"), name="brand-list"),
    path('brand/add/', BrandCreateView.as_view(template_name = "inventory/createview.html"), name='brand-add'),
    path('brand/<int:pk>/', BrandUpdateView.as_view(template_name = "inventory/createview.html"), name='brand-update'),
    path('brand/<int:pk>/delete/', BrandDeleteView.as_view(template_name = "inventory/deleteview.html"), name='brand-delete'),

    # attribute (atb)

    path('atb-list', AtbList.as_view(template_name="inventory/atb-list.html"), name="atb-list"),
    path('atb/add/', AtbCreateView.as_view(template_name = "inventory/createview.html"), name='atb-add'),
    path('atb/<int:pk>/', AtbUpdateView.as_view(template_name = "inventory/createview.html"), name='atb-update'),
    path('atb/<int:pk>/delete/', AtbDeleteView.as_view(template_name = "inventory/deleteview.html"), name='atb-delete'),

    # products 

    path('prod-list', ProdList.as_view(template_name="inventory/prod-list.html"), name="prod-list"),
    path('prod/add/', ProdCreateView.as_view(template_name = "inventory/createview.html"), name='prod-add'),
    path('prod/<int:pk>/', ProdUpdateView.as_view(template_name = "inventory/createview.html"), name='prod-update'),
    path('prod/<int:pk>/delete/', ProdDeleteView.as_view(template_name = "inventory/deleteview.html"), name='prod-delete'),

    # inventories (inv)

    path('inv-list', InvList.as_view(template_name="inventory/inv-list.html"), name="inv-list"),
    path('inv/add/', InvCreateView.as_view(template_name = "inventory/createview.html"), name='inv-add'),
    path('inv/<int:pk>/', InvUpdateView.as_view(template_name = "inventory/createview.html"), name='inv-update'),
    path('inv/<int:pk>/delete/', InvDeleteView.as_view(template_name = "inventory/deleteview.html"), name='inv-delete'),

]

frontend/models.py
from django.db import models

# Create your models here.

inventory/models.py
from pickle import TRUE
from django.db import models
from datetime import datetime, timedelta
from django.utils.translation import gettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.
class Categories(models.Model) :
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self) -> str:
        return self.title


class Attributes(models.Model) :
    value = models.CharField(max_length=100)
    def __str__(self) -> str:
        return self.value

class Brand(models.Model) :
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name


class Product(models.Model) :
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=255)
    image = models.ImageField(upload_to ="images/", default="images/default.png")
    # thumbnail
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(100, 100)],
                                      format='JPEG',
                                      options={'quality': 60})


    # foreign keys
    category = models.ManyToManyField(Categories)
    brand = models.ForeignKey(Brand, on_delete=models.RESTRICT)

    def __str__(self) -> str:
        return self.title



class ProductInventory(models.Model) :

    class Variants(models.IntegerChoices) :
        pro = 3
        native = 2
        lite = 1

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version = models.SlugField(unique=True, max_length=100)
    # attributes
    customAttribute = models.ForeignKey(Attributes, on_delete=models.RESTRICT, blank=True, null=True)
    variant = models.IntegerField(choices=Variants.choices, default=2)   

    # prices
    price = models.IntegerField()

    # stock
    stock = models.IntegerField(default=0)
    sold = models.IntegerField(default=0)
    debitDate = models.DateTimeField(default=datetime.utcnow()+timedelta(hours=5.5), 
    help_text=_(
        "format: required, YYYY-MM-DD HH:MN:SC (2022-01-19 17:29:19) "
    ),

    )
    creditDate = models.DateTimeField(default=datetime.utcnow()+timedelta(hours=5.5),
    help_text=_(
    "format: required, YYYY-MM-DD HH:MN:SC (2022-01-19 17:29:19) "
    ),
    )


    def __str__(self) -> str:
        return self.version

frontend/views.py
from curses.panel import version
from unicodedata import category
from django.shortcuts import render
from inventory.models import Categories, Product, ProductInventory
from django.db.models import Count
from django.shortcuts import get_object_or_404

# Create your views here.
def categoriesList(request) :
    data = Categories.objects.all().annotate(
    product_count=Count('product'))

    return render(request, "frontend/categories.html", {"data": data})

def productPage(request, slug) :
    data = Product.objects.filter(category__slug = slug)
    catData = get_object_or_404(Categories , slug = slug)
    return render(request,"frontend/catprods.html",{"data":data,"catData":catData})

def inventories(request,slug) :
    data = ProductInventory.objects.filter(product__slug = slug)
    return render(request, "frontend/inventories.html",{"data":data})

def listProduct(request):
    data = Product.objects.all()
    return render(request,"frontend/catprods.html",{"data":data})

def inventory(request,slug) :
    data = get_object_or_404(ProductInventory,version=slug)
    # print(data.product.slug)
    categories = Categories.objects.filter(product__slug = data.product.slug)
    return render(request,"frontend/inventory.html", {"data":data, "categories":categories})

inventory/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import *
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy


class CategoryList(ListView) :
    model = Categories


class CategoryCreateView(CreateView):
    model = Categories
    fields = '__all__'
    success_url = reverse_lazy('inventory:cat-list')

class CategoryCreateView(CreateView):
    model = Categories
    fields = '__all__'
    success_url = reverse_lazy('inventory:cat-list')

class CategoryUpdateView(UpdateView):
    model = Categories
    fields = '__all__'
    success_url = reverse_lazy('inventory:cat-list')

class CategoryDeleteView(DeleteView):
    model = Categories
    success_url = reverse_lazy('inventory:cat-list')


# brand


class BrandList(ListView) :
    model = Brand


class BrandCreateView(CreateView):
    model = Brand
    fields = '__all__'
    success_url = reverse_lazy('inventory:brand-list')

class BrandCreateView(CreateView):
    model = Brand
    fields = '__all__'
    success_url = reverse_lazy('inventory:brand-list')


class BrandUpdateView(UpdateView):
    model = Brand
    fields = '__all__'
    success_url = reverse_lazy('inventory:brand-list')

class BrandDeleteView(DeleteView):
    model = Brand
    success_url = reverse_lazy('inventory:brand-list')


# Attribute


class AtbList(ListView) :
    model = Attributes


class AtbCreateView(CreateView):
    model = Attributes
    fields = '__all__'
    success_url = reverse_lazy('inventory:atb-list')

class AtbCreateView(CreateView):
    model = Attributes
    fields = '__all__'
    success_url = reverse_lazy('inventory:atb-list')


class AtbUpdateView(UpdateView):
    model = Attributes
    fields = '__all__'
    success_url = reverse_lazy('inventory:atb-list')

class AtbDeleteView(DeleteView):
    model = Attributes
    success_url = reverse_lazy('inventory:atb-list')


# products (prod)


class ProdList(ListView) :
    model = Product


class ProdCreateView(CreateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('inventory:prod-list')

class ProdCreateView(CreateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('inventory:prod-list')


class ProdUpdateView(UpdateView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('inventory:prod-list')

class ProdDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('inventory:prod-list')


# inventories



class InvList(ListView) :
    model = ProductInventory


class InvCreateView(CreateView):
    model = ProductInventory
    fields = '__all__'
    success_url = reverse_lazy('inventory:inv-list')

class InvCreateView(CreateView):
    model = ProductInventory
    fields = '__all__'
    success_url = reverse_lazy('inventory:inv-list')


class InvUpdateView(UpdateView):
    model = ProductInventory
    fields = '__all__'
    success_url = reverse_lazy('inventory:inv-list')

class InvDeleteView(DeleteView):
    model = ProductInventory
    success_url = reverse_lazy('inventory:inv-list')

templates/frontend/categories.html
{% extends 'base.html' %}

{% block content %}
    
    <p>
        Please select from the following categories. <br/>
        The number in () indicates the number of products present per category.
    </p>

    <ol>
        {% for x in data %}
        {% if x.product_count %}
        <li>
            <a href="{% url 'frontend:productPage' x.slug %}">{{x.title}}</a> ({{x.product_count}})
        </li>
        {% else %}
        <li class="text-muted">
            {{x.title}} ({{x.product_count}})
        </li>
        {% endif %}
        {% endfor %}
    </ol>

    
{% endblock %}

templates/frontend/catprods.html
{% extends 'base.html' %}

{% block content %}
    

{% if data %}
<div class="container">

{% if catData %}
<h3 align="center">
    {{catData.title}}
</h3>
{% endif %}

<div class="container text-center">

    {% for x in data %}

    <div class="card text-center" style="width: 18rem;">
        {% if x.image_thumbnail %}
        <img class="card-img-top" src="{{x.image_thumbnail.url}}" alt="Card image cap">
        {% else %}
        <img class="card-img-top" src="{{x.image.url}}" alt="Card image cap">
        {% endif %}

        <div class="card-body">
          <h5 class="card-title">{{x.title}}</h5>
          <p class="card-text">{{x.description}}</p>
          <!-- <a href="{{x.slug}}">HI</a> -->
          <a href="{% url 'frontend:inventories' x.slug %}" class="btn btn-primary">details</a>
          <hr>
          Product by {{x.brand}}
        </div>
    </div>
    <br>

    {% endfor %}

  
</div>
{% else %}
Please add some products to list some products here
{% endif %}

{% endblock %}

templates/frontend/index.html
{% extends 'base.html' %}
{% block content %}
    Welcome to Inventory Management System 
    <br/>


    <ul>
        <li>
            Please find the available <a href="{% url 'frontend:list-products' %}"> products </a>
        </li>
        <li>
            Or explore the <a href="{% url 'frontend:categories-list' %}"> categories </a>
            
        </li>
        <li>
            or <a href="{% url 'inventory:index' %}">add/delete/update</a> an item from our database.
        </li>

    </ul>


{% endblock %}

templates/frontend/inventories.html
{% extends 'base.html' %}

{% block content %}

{% if data %}
<p>
    Choose from the following variants of the product {{product}}
</p>

<div class="container">

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Version </th>
            <th scope="col">Variant</th>
            <th scope="col">Custom Attribute</th>
            <th scope="col">Price </th>
        </tr>
        </thead>
        <tbody>

            {% for product in data %}
            

        <tr>
            <td> 
                <a href="{% url 'frontend:inventory' product.version %}">  
                {{ product.version }} </a> 
            </td>
            <td> {{ product.get_variant_display }} </td>
            <td> {{ product.customAttribute }} </td>
            <td> $ {{ product.price }}  </td>
        </tr>

            {% endfor %}

        </tbody>
    </table>

</div>
    
{% else %}

No inventory exist for the selected product, please visit later.

{% endif %}

{% endblock %}

templates/frontend/inventory.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<link rel="stylesheet" href="{% static 'frontend/inventory.css' %}">
{% endblock %}


{% block content %}
<div class="container">

        <h6 align="center">
            {{data.product.title}} {{data.version}}
        </h6>

        <br/>

        <h2>
            Specifications
        </h2>

        <div class="container box">
            <div class="left">
                <div class="card">
                    {% if data.product.image_thumbnail %}
                    <img class="card-img-top" src="{{data.product.image_thumbnail.url}}" alt="Card image cap">
                    {% else %}
                    <img class="card-img-top" src="{{data.product.image.url}}" alt="Card image cap">
                    {% endif %}           
                </div>
            </div>
            <div class="right">

                <div class="container inside">
                    
                    <button class="btn btn-info">{{data.get_variant_display}}</button>
                    <br>
 
                    <h6>Attributes </h6> 
                    <ul>
                        <li>
                            Version - {{data.version}}
                        </li>
                        <li>
                            <p style="max-width: 50vw;">
                                {{data.product.description}}
                            </p>
                        </li>
                        <li>
                            Custom Attribute - {{data.customAttribute}}
                        </li>
                        <li>
                            Build by - {{data.product.brand}}
                        </li>


                    </ul>
                   
                    <button class="btn btn-danger">Price - $ {{data.price}}</button>
                    <hr>
                    <h6>
                        Stock Information
                    </h6>
                    
                    <ul>
                        <li>
                            Sold - {{data.sold}}
                        </li>
                        <li> In Stock - {{data.stock }} </li>
                        <li> Last Credit on - {{data.creditDate}} </li>
                        <li> Last Debited on - {{data.debitDate}}</li>
                        
                    </ul>

                    <hr>
                    <h6>
                        Related Categories (Links redirect to category page)
                    </h6>

                    <div class="container">
                        {% for category in categories %}
                        <a href="{% url 'frontend:productPage' category.slug %}" class="btn btn-primary"> 
                            {{category.title}} </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <br>


</div>

{% endblock %}